### ISSUE TITLE
Adapt for CO2 Calibration in header for UPASv2+ later firmware

### ISSUE THREAD

**Issue by gneymark** [accsensors/astr#20]
Read_ast_header() in ast.r throws following error on v2+ files since it is not expecting the CO2 calibration lines added to the firmware

Warning message:
In data.table::fread(file = file, skip = 0, nrows = 100, sep = ",",  :
  Stopped early on line 70. Expected 3 fields but found 112. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<DateTime,DateTime,DateTime,DateTime,DateTime,FilterSample,FilterSample,FilterSample,FilterSample,Battery,Atmo,Atmo,Atmo,Atmo,Atmo,GPS,GPS,GPS,GPS,GPS,GPS,GPS,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Motion,Light,Light,Light,Light,Light,Light,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor,PMSensor>>

**Comment by jtryner** [comment]
I think it actually shows this warning when it sees the sample log columns.  The header data are organized into 3 columns, but there are 100+ columns in the sample log.
